version: '3.8'
services:
  genspark2api:
    container_name: genspark2api
    image: rfym21/genspark2api:latest
    restart: always
    build: .
    ports:
      - "3000:8666"
    volumes:
      - ./data:/app/data
    environment:
      # 接口路径
      - API_PATH=
      # 每次生成图片数
      - IMAGE_COUNT=1
      # 每张图片图片等待时间(共四张)
      - IMAGE_WAIT_TIME=30000
      # 请求身份验证(非0模式可用)
      - API_KEY=sk-123456
      # 代理配置
      # 0: 不使用代理
      # 1: 使用单代理
      - PROXY_MODE=0
      # 代理地址
      - PROXY_URL=socks5://username:password@host:port
      # 代理api
      - PROXY_API=

